### ISSUE TITLE
remove unnecessary uncommitted size reduction after leadership changes

### ISSUE THREAD

**Issue by nvanbenschoten** [etcd-io/raft#12]
Related to https://github.com/etcd-io/raft/issues/11.

In `becomeLeader`, we have the following logic:
https://github.com/etcd-io/raft/blob/91eb7518afb589ac295f9fa3b837a11c48cc8682/raft.go#L792-L796

This is a no-op. The payload size of `emptyEnt` is 0, so there's no need to subtract it from the uncommitted size accounting.

If we delete the line, all tests pass. Let's delete it and then add a unit test verifying that `payloadsSize(emptyEntry) == 0` with a suitable comment explaining why this is an important property.

**Comment by kriti-sc** [comment]
I would like to pick this up. @tbg @nvanbenschoten

**Comment by daman1807** [comment]
Hi @tbg @nvanbenschoten can you look into this
https://github.com/etcd-io/raft/pull/17
