### ISSUE TITLE
Enable ARM64 GitHub workflows

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/raft#122]
This is nice to have, as discussed in the fortnightly etcd community meeting. But given that etcd has official support for ARM, it's important to run GitHub workflows using ARM64 runners.

This would be a good candidate for the good first issue label.

Refer to etcd-io/etcd#16801, etcd-io/bbolt#583 and the Pull Requests that close those issues.

**Comment by tcchawla** [comment]
Hey @jmhbnz, I would like to work upon this. Can you please assign this to me?
