### ISSUE TITLE
Question about transition from follower to candidate

### ISSUE THREAD

**Issue by justlorain** [etcd-io/raft#143]
Sorry to bother. 
While reviewing the code, I noticed that there is no check for whether a follower has already voted for another candidate during the transition to becoming a candidate. However, according to the second rule for Followers in the Rules for Servers section of the Raft paper, such a check should be performed. If possible, I would like to understand the reason for omitting this check in this particular implementation.

The original text of the paper is as follows:
```
Followers (§5.2):
• Respond to RPCs from candidates and leaders
• If election timeout elapses without receiving AppendEntries
RPC from current leader or granting vote to candidate:
convert to candidate
```

**Comment by pav-kv** [comment]
Hi @justlorain. My understanding is that this part of the protocol is not responsible for correctness - it's a heuristic aiming to understand that the leader hasn't sent any messages recently.

The "correctness" requirement is that we don't cast a vote at term `t` to 2 different candidates. The rules for when to become a candidate can be implemented differently.

**Comment by pav-kv** [comment]
Also, we do seem to [reset](https://github.com/etcd-io/raft/blob/026484c68b7bc59cd208e216d35e1ff747d24d9c/raft.go#L1203-L1207) the heartbeat tick to 0 when casting a vote. This effectively implements the "granting vote" part of the rule you quoted.

**Comment by justlorain** [comment]
Thank you for your detailed response; it has been very helpful to me.
