### ISSUE TITLE
Question about Prevote

### ISSUE THREAD

**Issue by 1797818494** [etcd-io/raft#159]
I wonder how etcd raft prevote make sure that at least one preCandidate will become Candidate? When I try to implement raft. I find that one case will deadlock. 5 nodes{1, 2, 3, 4, 5}. 3 become leader. node 2, node 1 can conneted the leader, but others can't. node 3 proposes one confchange(remove 3). At last, I find the node states{ node 1 (term 6, vote 3, latest log), node 2 (term 6, vote 3 latest log) node 4 (term 7 vote 5) node 5(term 7 vote 5)}.They are deadlock. Wonder how etcd raft solve this.

**Comment by pav-kv** [comment]
> I wonder how etcd raft prevote make sure that at least one preCandidate will become Candidate?

The condition is that a node receives a prevote from a quorum of nodes. It's hard to read your described scenario, but: if nodes 4 and 5 are partitioned from the rest of the cluster then, after removing node 3, it's not possible for any node to get a quorum of (pre-)votes. You need 3 votes in a 4-node cluster.

**Comment by 1797818494** [comment]
> > I wonder how etcd raft prevote make sure that at least one preCandidate will become Candidate?
> 
> The condition is that a node receives a prevote from a quorum of nodes. It's hard to read your described scenario, but: if nodes 4 and 5 are partitioned from the rest of the cluster then, after removing node 3, it's not possible for any node to get a quorum of (pre-)votes. You need 3 votes in a 5- or 4-nodes cluster.
> 
> If you are removing node 3 with a goal of adding another node to replace it, then you should propose a confchange that does both operations simultaneously. If the new node is not partitioned from nodes 1 and 2, then some node in (1, 2, newNode) will win election.
node 1 (term 6, vote 3, latest log), node 2 (term 6, vote 3 latest log) node 4 (term 7 vote 5) node 5(term 7 vote 5).It seems that no one node in preCandidate can get 3 votes success in the 4 node cluster.And preCandidate failure not change the condition(node's term and vote).node 1 and 2 fail because its prevote term = 7 but node 4 or 5 is vote 5. node 4, 5 fail because the log is not updated as 1, 2

**Comment by pav-kv** [comment]
Can you state more clearly the partitioning between the nodes. Are nodes 4 and 5 connected with nodes 1 and 2 in the 4-nodes cluster? If not, then it is expected that noone can get a quorum of nodes in this cluster. If they were connected, then the fact that nodes 4 and 5 have outdated logs does not prevent nodes 1 or 2 winning election.

**Comment by 1797818494** [comment]
can conneted. https://github.com/etcd-io/raft/blob/main/raft.go#L1187 but the canVote is false when nodes 4 or 5 receive the prevote because the vote term equal and they already vote for 5

**Comment by pav-kv** [comment]
Nodes 4 and 5 will be able to vote for higher terms. Eventually, some node will bump the term to high enough value and will be able to get votes from nodes 4 and 5 if they are connected.

**Comment by pav-kv** [comment]
If you think there is a deadlock (probably you mean "livelock"), please submit a PR with a test that demonstrates it. So far, I don't see any issue.

**Comment by pav-kv** [comment]
The `Term` should be bumped on every election timeout here: https://github.com/etcd-io/raft/blob/59637807b08316f7a30ece323321dc38df08f34e/raft.go#L835

Eventually, the `Term` will exceed all previous terms, and the node will be able to get votes.

**Comment by pav-kv** [comment]
I see what you're saying. Are you saying that when PreVote is enabled, we will never bump the term?

https://github.com/etcd-io/raft/blob/59637807b08316f7a30ece323321dc38df08f34e/raft.go#L893

**Comment by 1797818494** [comment]
Yes

**Comment by 1797818494** [comment]
preCandidate will increase term here like Candidate. https://github.com/etcd-io/raft/blob/main/raft.go#L1094
Previously in my implement, I ignore the point because I think preCandidate's goal is that make sure the term not increase.But they can.Because the only reasons determined the precandidate are network and logs.It's not really important that term increase or not.
