### ISSUE TITLE
Nominate @erikgrinaker as a raft member

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/raft#163]
I believe @erikgrinaker meets all the [requirement](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md#requirements) of a member (The only exception might be subscribing to etcd-dev, please ping me back when you finish subscribing the group @erikgrinaker). 
-  All his contribution can be found [here](https://github.com/etcd-io/raft/pulls?q=is%3Apr+author%3Aerikgrinaker+is%3Aclosed). He has already demonstrated deep understanding on raft.
- He is an active contribution on the raft project.
- He is also a de-fact reviewer.

cc @pav-kv @serathius @spzala 
@jmhbnz @wenjiaswe

**Comment by jmhbnz** [comment]
+1, thanks @erikgrinaker (and @ahrtr for raising)

**Comment by serathius** [comment]
+1

**Comment by ahrtr** [comment]
@erikgrinaker can you please raise a formal request (issue) in https://github.com/kubernetes/org/issues? 
- Please list @ahrtr and. @serathius as the sponsor (thx the support from @jmhbnz and @pav-kv as well).
- Select the organization : **etcd-io**

**Comment by erikgrinaker** [comment]
Yep, done: https://github.com/kubernetes/org/issues/4763

Thanks!

**Comment by jmhbnz** [comment]
Completed under https://github.com/kubernetes/org/pull/4767.

@erikgrinaker can I please double check you received an etcd-io org invite?  This is our first iteration of using the kubernetes project org management automation so want to make sure it all worked ok 🙏🏻

**Comment by erikgrinaker** [comment]
Thanks all!

> can I please double check you received an etcd-io org invite?

For the GitHub org? I'm not seeing an invite anywhere in my email accounts, nor in my GitHub account.

**Comment by ahrtr** [comment]
@erikgrinaker Please double check whether you have received an invitation to join th etcd-io org.

https://github.com/kubernetes/org/pull/4767#issuecomment-1947962667

**Comment by erikgrinaker** [comment]
Yep, I'm in!

**Comment by ahrtr** [comment]
Great!
