### ISSUE TITLE
github.com/getsentry/raven-go is archived

### ISSUE THREAD

**Issue by pacoxu** [etcd-io/raft#19]
https://github.com/etcd-io/raft/blob/7357439323abcd0654b7146022f7a58793d667eb/go.mod#LL7C43-L7C57

This is using an old version of https://github.com/cockroachdb/datadriven/commit/c9e8355525148c6ef1ede0f757e0c4111cc318f2

Would you upgrade to v1.0.0 or later?

follow up of https://github.com/kubernetes/kubernetes/pull/114912.

**Comment by tbg** [comment]
Thank you!
