### ISSUE TITLE
Please provide a simple and clean example

### ISSUE THREAD

**Issue by wind-c** [etcd-io/raft#30]
The etcd example is too dependent and complex. This raft library stands alone and is difficult to adopt widely if it still relies on etcd.

**Comment by ahrtr** [comment]
Duplicated to https://github.com/etcd-io/raft/issues/2

**Comment by Elbehery** [comment]
Thanks @ahrtr  

I am working on #2  this weekend 

deep apologies for the delay, i am really back2back
