### ISSUE TITLE
Cluster struggles to elect leader when all peers are started at the same time

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/raft#48]
Please refer to https://github.com/etcd-io/etcd/issues/15784

**Comment by CaojiamingAlan** [comment]
@ahrtr Please review #50, thanks

**Comment by pavelkalinnikov** [comment]
Closing since #50 has been merged.

**Comment by stevenengler** [comment]
Thanks @CaojiamingAlan for the patch!
