### ISSUE TITLE
Nominate pavelkalinnikov as reviewer

### ISSUE THREAD

**Issue by tbg** [etcd-io/raft#59]
I'd like to nominate @pavelkalinnikov as a reviewer (in the sense of the etcd community guidelines[^2]) for etcd-io/raft starting in mid-July 2023[^4]

As of mid-April, Pavel is [recognized](https://github.com/etcd-io/etcd/issues/15714) as an etcd/etcd-io member owing to his contributions to etcd-io/raft. As you can see from the references within and his activity since, Pavel has been very active on the raft codebase, fixing bugs, adding new functionality and documentation, and is starting to reflect on the future direction of the library as well (e.g. [^3]). As Pavel's co-worker on the Replication team at Cockroach Labs, I can attest to his intimacy with both consensus algorithms and their real-world deployment at scale and further foster his involvement with our community.

[^1]: https://github.com/etcd-io/raft/pull/58
[^3]: https://github.com/etcd-io/raft/issues/64
[^4]: at which he will clear the three-month minimum membership duration stipulated in [^2]

cc @ahrtr @mitake @ptabor @serathius @spzala

----

2023-05-31: edited to reflect outcome of discussion among maintainers about how to apply the community guidelines[^2]

[^2]: https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md

**Comment by spzala** [comment]
+1 @pavelkalinnikov congratulations and thank you for your ongoing contributions to the project! @tbg  thank you so much for your years of leadership in the Raft area!

**Comment by ahrtr** [comment]
Completed by https://github.com/etcd-io/raft/pull/87

**Comment by pavelkalinnikov** [comment]
Thanks everyone.
